export const CHAT_MESSAGE_TYPE_NORMAL = 'NORMAL';
export const CHAT_MESSAGE_TYPE_SYSTEM = 'SYSTEM';
export const SYSTEM_CHAT_MESSAGE_ROOM_CREATED = 'SYSTEM_CHAT_MESSAGE_ROOM_CREATED';
export const SYSTEM_CHAT_MESSAGE_ROOM_MEMBER_JOINED = 'SYSTEM_CHAT_MESSAGE_ROOM_MEMBER_JOINED';
