export const MESSAGE_ROOM = {
  ROOM: 'ROOM',
  CREATE_ROOM: 'ROOM/CREATE_ROOM',
  JOIN_ROOM: 'ROOM/JOIN_ROOM',
  NEW_ROOM_MEMBER_JOINED: 'NEW_ROOM_MEMBER_JOINED'
};

export const MESSAGE_CHAT = {
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  SEND_ROOM_CHAT_MESSAGE: 'CHAT_MESSAGE/SEND_ROOM_CHAT_MESSAGE',
  ROOM_CHAT_MESSAGE: 'CHAT_MESSAGE/ROOM_CHAT_MESSAGE'
};
