export const MESSAGE_ROOM = {
  ROOM: 'ROOM',
  CREATE_ROOM: 'ROOM/CREATE_ROOM'
};

export const MESSAGE_CHAT_MESSAGE = {
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  SEND_CHAT_MESSAGE: 'CHAT_MESSAGE/SEND_MESSAGE'
};
